### ISSUE TITLE
Golf

### ISSUE THREAD

**Issue by JKerb** [Java2Class/Project-3-Java-2-Programming#31]
Reminder that we need use cases.  So far I have these.  If anyone has any more suggestions please feel free to share.

Player registers for game
Player plays the game -Silvey
Player ends the game(turns in card and gets printout) -Haven
Employee issues replacement card (lost card) -Kerb
Admin wipes database records (daily? weekly? monthly?)

**Comment by ChrisEngineer** [comment]
Player highers Caddy for course? Player chooses course to play on? player picks Clubs to play with? -Chris

**Comment by JSilvey** [comment]
I don't think you need a caddy or different clubs to play mini golf.

**Comment by ChrisEngineer** [comment]
It could be a mini golf program as in a small scale, not mini golf as in miniature golf like you would play at universal

**Comment by JKerb** [comment]
I think it's probably putt putt golf.  Anyway, I made some decision trees for the RFP, and my use case.  If anyone needs me to change anything, please let me know.

The PLAYER decision tree:
![player decision tree golf](https://cloud.githubusercontent.com/assets/10632865/7307002/5e61b290-e9d7-11e4-94bb-dc6fc43b9107.png)

The EMPLOYEE decision tree:
![emp decision tree golf](https://cloud.githubusercontent.com/assets/10632865/7307004/6696ae84-e9d7-11e4-9a61-40745509ef9d.png)

The ADMIN decision tree:
![admin decision tree golf](https://cloud.githubusercontent.com/assets/10632865/7307009/6f05f282-e9d7-11e4-8ac8-533c3f538154.png)

Use Case:
Use Case # N: Employee Prints Replacement Card
    a. System presents employee with authentication request.
    b. Employee enters user name and password.
    c. System presents employee with Employee Main Menu.
    d. Employee selects Transaction from the Employee Main Menu.
    e. System presents employee with Transaction Menu.
    f. Employee selects Print Card option.
    g. System requests first and last name for lookup.
    h. Employee enters first and last name of golfer.
    i. System searches database for golfer, based on newest entry.
    j. System presents Employee with record for golfer.
    k. Employee prints a new card with golfer information.
    l. System returns to Transaction Menu.

**Comment by JSilvey** [comment]
![playerplays](https://cloud.githubusercontent.com/assets/10662323/7327789/e5646d34-ea9d-11e4-9248-e8c778d4f792.JPG)

Use Case:
Use Case # N: Player Plays A Hole
a. System asks user to swipe player card or key in player card number (in case of damaged card or scanner).
b. User swipes card or enters number on keypad.
c. System retrieves player name, current score, and current hole information.
d. System Prompts user to enter stroke count for current hole.
e. Player enters stroke count on keypad.
f. System prompts user "Is this number correct" message box noting that the score can not be changed once entered.
g. User enters either yes to confirm stroke number or no to correct stroke number.
h1. User enters Yes- System records player stroke number for hole and adds it to player score.
h1a. System returns to start screen ready for next player (step: a).
h2. User enters No- System returns to step: d to prompt user to enter stroke count for current hole. This loop continues until the user enters Yes in step: G.

**Comment by JSilvey** [comment]
Let me know if this is sufficient. If not, please suggest what else I can add. Thanks

**Comment by ChrisEngineer** [comment]
What about if the user is not a member and doesn't want a card? Can't they play as a guest ?

**Comment by JSilvey** [comment]
According to the project description the system is designed to automate a putt putt golf course to replace the standard pencil and scorecard method. The way i understand it is these stations will be at every hole on the course and every player gets a card instead of a traditional score card. There is no membership option (at least not in the assignment specs).

**Comment by scrizz** [comment]
What about if the machine jams. Can the user reprint his/her score?

Maybe employees/admins should be able to edit the users score just incase they(users) made a typo.

The system should also let users end the game early.

**Comment by JKerb** [comment]
This is all well and good but remember you guys need to write use cases for each one of these things you are bringing up.  Preferably early enough so that Haven has time to write the RFP.  I have modified the admin and employee decision trees.

EMPLOYEE:
![emp decision tree golf 2](https://cloud.githubusercontent.com/assets/10632865/7335220/e06e0416-eb7e-11e4-9c9d-117f2fefe4cb.png)

ADMIN:

![admin decision tree golf 2](https://cloud.githubusercontent.com/assets/10632865/7335211/624ec3d6-eb7e-11e4-984e-e63af0fe6e61.png)

If this is what you want to do.  Now employees can modify records.  IMO a user doesn't need to end the game early, he can just tell the guy at the register and cash out.  His record will be purged by the admin later.

**Comment by scrizz** [comment]
Use Case:
Use Case # N: Employee Edits User Record
a. System presents employee with authentication request.
b. Employee enters user name and password.
c. System presents employee with Employee Main Menu.
d. Employee selects Transaction from the Employee Main Menu.
e. System presents employee with Transaction Menu.
f. Employee selects Player Record
g. System presents employee with Player Record Menu.
h. Employee selects Edit Record option.
i. System requests first and last name for lookup.
j. Employee enters first and last name of golfer.
k. System searches database for golfer, based on newest entry.
l. System presents Employee with record for golfer.
m. Employee edits golfer score information.
n. System returns to Transaction Menu.

**Comment by JKerb** [comment]
Noice.

Use Case:
Use Case # N: Administrator Purges Database
a. System presents admin with authentication request.
b. Admin enters user name and password.
c. System presents employee with Admin Main Menu.
d. Admin selects Database Management from the Admin Main Menu.
e. System presents employee with Database Management Menu.
f. Admin selects Purge Database option.
g. System shows admin a yes/no dialog for confirmation.
h. Admin clicks yes.
i. System purges all records in the database.
j. System presents Admin with Database Management Menu.

**Comment by JSHaven** [comment]
I hope I'm doing this right. I'm doing the Players Ends the game. I also added a replay scenario just to be a bit more realistic. 

USE CASES FOR REPLAY:

Use Case:
Use Case #N: Player Replays Game (through console)
a.  Player access terminal
b.  Player types in name or card number.
c.  Player clicks "Replay" button after completing entire course. 
d.  Terminal prints out first score printout.
e.  Terminal erases previous game data.
f.  Player takes card.
g.  Player plays again.

Use Case:
Use Case #N: Player Replays Game (through employee)
a.  Player goes to employee
b.  Player gives card to employee to get previous score printout.
c.  Player takes previous game score printout.
d.  Player lets employee erase previous game data on card (system).
e.  Player takes card from employee.
f.  Player plays again.

Use Case:
Use Case #N: Employee Replays Game
a.  Player goes to employee
b.  Player gives card to employee.
c.  Employee logs in (if not already logged in).
d.  Employee goes to “Transaction section” in terminal.
e.  Employee accesses “Player Record”.
f.  Employee accesses “Print Record”.
g.  Employee access “Edit Record” (to clear the previous game).
h.  Employee accesses “Return to Transaction Menu”.
i.  Employee access “Cash Out” (to pay for the game).
j.  Employee access “Return to Main Menu”.
k.  Employee gives player card.

USE CASE FOR END GAME:

Use Case:
Use Case #N: Player Ends Game (through console)
a.  Player access terminal
b.  Player types in name or card number.
c.  Player clicks “End Game” button after completing entire course. 
d.  Terminal prints out score printout.
e.  Terminal erases previous game data.
f.  Player takes card.
g.  Player leaves.

Use Case:
Use Case #N: Player Ends Game (through employee)
a.  Player goes to employee
b.  Player gives card to employee to get score printout.
c.  Player takes game score printout.
d.  Player lets employee erase previous game data on card (system).
e.  Player takes card from employee.
f.  Player leaves.

Use Case:
Use Case #N: Employee Ends Game
a.  Player goes to employee
b.  Player gives card to employee.
c.  Employee logs in (if not already logged in).
d.  Employee goes to “Transaction section” in terminal.
e.  Employee accesses “Player Record”.
f.  Employee accesses “Print Record”.
g.  Employee access “Edit Record” (to clear the previous game).
h.  Employee accesses “Return to Transaction Menu”.
i.  Employee access “Cash Out” (to pay for the game).
j.  Employee access “Return to Main Menu”.
k.  Employee gives player card or throws it away.

Now, for Replay and End Game, I wasn't sure if we were charging them to play at the beginning (like most companies would) or the end since "Cash Out" hints last. If we will charge them at the beginning, the user cases will be changed a bit. Also, Employee Replays Game and Employee Ends Game are the same since the employee doesn't do anything different (except charging for a game. If the charge is at the beginning it will only be in the replay, not the end, but if the charge is at the end, then it's in both). and also I don't have Visio. I just based this off of what you already have.

**Comment by JSHaven** [comment]
Also depending on how often the data is wiped, erasing the data may not be important. Also, for replay, if we allow multiple game data to be attached to the player, then editing the data may not be necessary.
If anything only a new object or game data would be opened if the player replays the game.

**Comment by JKerb** [comment]
Looks fine to me.  Here's one for Player registers for game.  This should be everything:

Use Case:
Use Case # N: Player Registers for Game
a. System presents employee with authentication request.
b. Employee enters user name and password.
c. System presents employee with Employee Main Menu.
d. Player provides Name.
e. Employee selects Transaction from the Employee Main Menu.
f. System presents employee with Transaction Menu.
g. Employee selects Generate Player option.
h. System requests first and last name of player.
i. Employee enters first and last name of player.
j. System stores first and last name of player and generates an identifier.
k. System requests to print a card for player.
l. Employee confirms.
m. System prints card for player.
n. System returns to Transaction Menu.
o. Employee prints a new card with golfer information.
p. System returns to Transaction Menu.

**Comment by scrizz** [comment]
All looks good to me.

**Comment by JSHaven** [comment]
Sweet XD if you need anything else text me so I know you need me ^_^

**Comment by JKerb** [comment]
The RFP has been created and will be submitted by Haven.  I will be closing this thread tomorrow around 2PM.  Everyone, please don't forget to submit your own ratings for this project.  Thanks!

**Comment by JSHaven** [comment]
Okay I submitted the RFP and my evaluations. If you didn't turn in your work or if you have anything else to turn in, contact me and I can edit it and send it again, otherwise, this part is done. Good job XD
